### ISSUE TITLE
Create basic website template

### ISSUE THREAD

**Issue by poshaughnessy** [poshaughnessy/webxr-for-learning#1]

**Comment by sogen** [comment]
Hi, 
Hugo is easy to maintain and static (no database needed):
https://themes.gohugo.io/

**Comment by poshaughnessy** [comment]
Thanks @sogen. It turned out that it's only really one page at the moment, so I have just used some basic HTML and CSS for now, but yes good to consider using a static site generator once the website grows a bit!
