### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by poshaughnessy** [poshaughnessy/webxr-for-learning#8]
It would be nice to make a logo to go with the name 'Teleportal'!

**Comment by bvhme** [comment]
I wanted a logo that played with space, has bold colours and works in the hexagon open source sticker standard.

![teleportal](https://user-images.githubusercontent.com/1917629/39933875-09d5d688-553c-11e8-8572-e5895963833e.png)

**Comment by poshaughnessy** [comment]
This is aweome, thanks so much @bvhme ! :D
